// Real (approximate) footprint polygons, generated by scripts/trace-building-footprints.ts off
// the actual campus photo — see that script for how, and the 3D map backlog entry for why this
// replaces the earlier per-tag rectangle guesses. Points are [x, z] meters relative to the pin's
// own world position (see worldSpace.ts), matching how Building.tsx positions its <group>.
import footprints from "./buildingFootprints.json"

// used whenever a pin's roof couldn't be reliably traced (see the script's fallback count) — a
// plain small square rather than trying to guess a better size per tag, per this round's "same
// height, whatever, we'll add variation later" scope call
const FALLBACK_FOOTPRINT: [number, number][] = [
  [-4, -4],
  [4, -4],
  [4, 4],
  [-4, 4],
]

type FootprintEntry = { points: [number, number][]; fallback: boolean }

export function getBuildingFootprint(pinId: string): [number, number][] {
  const entry = (footprints as unknown as Record<string, FootprintEntry>)[pinId]
  if (!entry || entry.fallback || entry.points.length < 3)
    return FALLBACK_FOOTPRINT
  return entry.points
}
